apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
     server: localhost
     path: /nfsvolumes/pv0002

