apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
     path: /nfsvolumes/pv0001

