kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-che-workspace
  annotations:
    volume.beta.kubernetes.io/storage-class: "che-workspace"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
