#!/usr/bin/env bash

export LOCUST_RHCHE_PROTOCOL=${PROTOCOL}
export LOCUST_RHCHE_BASE_URI=${BASEURL}
export LOCUST_RHCHE_ACTIVE_TOKEN=${TOKEN}
export LOCUST_RHCHE_WEBSOCKET_ENDPOINT=${WEBSOCKET:-"websocket"}

echo "Values:"
echo "LOCUST_RHCHE_PROTOCOL:$LOCUST_RHCHE_PROTOCOL"
echo "LOCUST_RHCHE_BASE_URI:$LOCUST_RHCHE_BASE_URI"
echo "LOCUST_RHCHE_ACTIVE_TOKEN length:${#LOCUST_RHCHE_ACTIVE_TOKEN}"
echo "LOCUST_RHCHE_WEBSOCKET_ENDPOINT:$LOCUST_RHCHE_WEBSOCKET_ENDPOINT"

locust -f real-life.py
