# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
kind: Template
apiVersion: v1
metadata:
  labels:
    app: rhche
  name: rhche
objects:
- apiVersion: v1
  kind: ServiceAccount
  imagePullSecrets:
  - name: quay.io
  metadata:
    labels:
      app: rhche
    name: rhche
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rhche
    name: rhche-host
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 8087
      protocol: TCP
      targetPort: 8087
    selector:
      app: rhche
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: rhche
    name: rhche
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: rhche-host
    port:
      targetPort: http
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: rhche
    name: rhche
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: rhche
    strategy:
      rollingParams:
        timeoutSeconds: 10000
      type: Rolling
    template:
      metadata:
        labels:
          app: rhche
      spec:
        containers:
        - env:
          - name: CHE_FABRIC8_END2END_PROTECT_SECRET__KEY
            valueFrom:
              secretKeyRef:
                key: secret-key
                name: rhche-end2end-protection
                optional: true
          - name: CHE_FABRIC8_END2END_PROTECT_SITE__KEY
            valueFrom:
              secretKeyRef:
                key: site-key
                name: rhche-end2end-protection
                optional: true
          - name: CHE_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.password
                  name: rhche
          - name: CHE_JDBC_URL
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.url
                  name: rhche
          - name: CHE_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.username
                  name: rhche
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                  key: service.account.id
                  name: rhche
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                  key: service.account.secret
                  name: rhche
          - name: CHE_INFRA_OPENSHIFT_PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CHE_INFRASTRUCTURE_ACTIVE
            value: "openshift"
          - name: SENTRY_RELEASE
            value: ${IMAGE_TAG}
          - name: CHE_CORE_JSONRPC_PROCESSOR__MAX__POOL__SIZE
            valueFrom:
              configMapKeyRef:
                key: che.core.jsonrpc.processor.major.max.pool.size
                name: rhche
          - name: CHE_CORE_JSONRPC_PROCESSOR__QUEUE__CAPACITY
            valueFrom:
              configMapKeyRef:
                key: che.core.jsonrpc.processor.major.queue.capacity
                name: rhche
          envFrom:
          - configMapRef:
              name: rhche
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: rhche
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 8087
            name: metrics
          - containerPort: 8000
            name: http-debug
          readinessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 60
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 512Mi
        serviceAccountName: rhche
    triggers:
    - type: ConfigChange
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-che-rh-che-server
- name: IMAGE_TAG
  value: latest
