kind: Template
apiVersion: v1
metadata:
  labels:
    app: che
  name: che
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: che
    name: che
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: che
    name: che-host
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: che
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: che
    name: che-data-volume
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: che
    name: che
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: che
    strategy:
      recreateParams:
        timeoutSeconds: 10000
      type: Recreate
    template:
      metadata:
        labels:
          app: che
      spec:
        containers:
        - env:
          - name: CHE_HOST
            valueFrom:
              configMapKeyRef:
                key: che-host
                name: che
          - name: CHE_WORKSPACE_STORAGE
            valueFrom:
              configMapKeyRef:
                key: workspace-storage
                name: che
          - name: CHE_LOGS_DIR
            valueFrom:
              configMapKeyRef:
                key: che.logs.dir
                name: che
          - name: CHE_LOCAL_CONF_DIR
            valueFrom:
              configMapKeyRef:
                key: local-conf-dir
                name: che
          - name: CHE_INFRA_OPENSHIFT_PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CHE_PREDEFINED_STACKS_RELOAD__ON__START
            valueFrom:
              configMapKeyRef:
                key: che.predefined.stacks.reload_on_start
                name: che
          - name: CHE_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                key: log-level
                name: che
          - name: CHE_PORT
            valueFrom:
              configMapKeyRef:
                key: port
                name: che
          - name: CHE_DEBUG_SERVER
            valueFrom:
              configMapKeyRef:
                key: remote-debugging-enabled
                name: che
          - name: CHE_LIMITS_WORKSPACE_ENV_RAM
            valueFrom:
              configMapKeyRef:
                key: workspaces-memory-limit-max
                name: che
          - name: CHE_WORKSPACE_DEFAULT__MEMORY__MB
            valueFrom:
              configMapKeyRef:
                key: workspaces-memory-limit
                name: che
          - name: CHE_WORKSPACE_AUTO__START
            valueFrom:
              configMapKeyRef:
                key: enable-workspaces-autostart
                name: che
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                key: che-server-java-opts
                name: che
          - name: CHE_WORKSPACE_JAVA__OPTIONS
            valueFrom:
              configMapKeyRef:
                key: che-workspaces-java-opts
                name: che
          - name: CHE_INFRA_OPENSHIFT_TLS__ENABLED
            valueFrom:
              configMapKeyRef:
                key: che-openshift-secure-routes
                name: che
          - name: CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS
            valueFrom:
              configMapKeyRef:
                key: che-openshift-precreate-subpaths
                name: che
          - name: CHE_KEYCLOAK_GITHUB_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: keycloak-github-endpoint
                name: che
          - name: CHE_FABRIC8_MULTITENANT
            valueFrom:
              configMapKeyRef:
                key: che-fabric8-multitenant
                name: che
          - name: CHE_FABRIC8_USER__SERVICE_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: che-fabric8-user-service-endpoint
                name: che
          - name: CHE_FABRIC8_AUTH_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: che-fabric8-auth-endpoint
                name: che
          - name: CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL
            valueFrom:
              configMapKeyRef:
                key: che-fabric8-multicluster-oso-proxy-url
                name: che
          - name: CHE_DOCKER_ENABLE__CONTAINER__STOP__DETECTOR
            valueFrom:
              configMapKeyRef:
                key: che-docker-enable-container-stop-detector
                name: che
          - name: CHE_API
            valueFrom:
              configMapKeyRef:
                key: che-api
                name: che
          - name: CHE_WEBSOCKET_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: che-websocket-endpoint
                name: che
          - name: CHE_WORKSPACE_LOGS_ROOT__DIR
            valueFrom:
              configMapKeyRef:
                key: che-workspace-logs
                name: che
          - name: CHE_KEYCLOAK_AUTH__SERVER__URL
            valueFrom:
              configMapKeyRef:
                key: che-keycloak-auth-server-url
                name: che
          - name: CHE_KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                key: che-keycloak-realm
                name: che
          - name: CHE_KEYCLOAK_CLIENT__ID
            valueFrom:
              configMapKeyRef:
                key: che-keycloak-client-id
                name: che
          - name: CHE_HOST
            valueFrom:
              configMapKeyRef:
                key: che-host
                name: che
          - name: CHE_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.password
                  name: che
          - name: CHE_JDBC_URL
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.url
                  name: che
          - name: CHE_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.username
                  name: che
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                  key: service.account.secret
                  name: che
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                  key: service.account.id
                  name: che
          - name: CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD
            valueFrom:
              configMapKeyRef:
                key: che-workspace-server-ping-success-threshold
                name: che
          - name: CHE_LIMITS_USER_WORKSPACES_RUN_COUNT
            valueFrom:
              configMapKeyRef:
                key: che-limits-user-workspaces-run-count
                name: che
          - name: CHE_INFRASTRUCTURE_ACTIVE
            value: "openshift"
          - name: CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL
            valueFrom:
              configMapKeyRef:
                key: infra-bootstrapper-binary-url
                name: che
          - name: CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN
            valueFrom:
              configMapKeyRef:
                key: infra-machine-start-timeout
                name: che
          - name: CHE_INFRA_KUBERNETES_PVC_STRATEGY
            valueFrom:
              configMapKeyRef:
                key: infra-pvc-strategy
                name: che
          - name: CHE_INFRA_KUBERNETES_TRUST__CERTS
            valueFrom:
              configMapKeyRef:
                key: infra-trust-certs
                name: che
          - name: CHE_MULTIUSER
            valueFrom:
              configMapKeyRef:
                key: multi-user
                name: che
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: che
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 8000
            name: http-debug
          readinessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 60
          resources:
            limits:
              memory: 750Mi
            requests:
              memory: 256Mi
          volumeMounts:
          - mountPath: /data
            name: che-data-volume
        serviceAccountName: che
        volumes:
        - name: che-data-volume
          persistentVolumeClaim:
            claimName: che-data-volume
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: che
    name: che
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: che-host
parameters:
- name: IMAGE
  value: rhche/che-server
- name: IMAGE_TAG
  value: latest
